### ISSUE TITLE
appsys undefined

### ISSUE THREAD

**Issue by uwelehmann** [AxeMenu/axemenu-jessie#1]
Hi,
I installed the extention axemenu-jessie in debian jessie but it doesnt work.
My log tells me something like "get_tree() on a non object" in extention.js Line 978
I did a litle search and I think this appsys is deprecated - and you must use something like:
new GMenu.Tree( {menu_basename: 'applications.menu' } );

Debian Jessie will be relased soon I think - please update.

**Comment by ViacheslavL** [comment]
Hello, thanks for the report.

Please, check the latest version, It works fine on my system

**Comment by uwelehmann** [comment]
thanks,
I had to change only the uuid value in metadata.json to "axemenu@jessie" and it worked.

Now I see only some visual differences to my wheezy axemenu:
- the round background around the search field is missing
- if I click 'Alle Anwendungen' (all applications) I dont see the left column with the main groups
  ... maybe this has something to do with running jessie in virtual box at 1024x768px.

**Comment by ViacheslavL** [comment]
Hello, thanks again, 

I'll try to start it on lower screen resolutions. On 1920x1080 it runs fine.

On search field I have opened a new issue, this will be closed.
